# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4.2
  SuggestExtensions: true

Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
RSpec/NestedGroups:
  Enabled: false
RSpecRails/InferredSpecType:
  Enabled: false

Style/Documentation:
  Enabled: false
